Type hints (#6)
* Initial type hinting on a few files
Added mypy config file

* Added type hints to augmentor.py and updated mypy.ini

augmentor.py still has the below error, which requires a fix:

src/tsaug/augmentor.py:212: error: Unsupported operand types for * ("None" and "int")
src/tsaug/augmentor.py:212: note: Left operand is of type "Optional[int]"

* Updated augmentor.py with lastest patch and hints

* Type hinted cross_sum.py added black config file

* Added type hints to dimensionalize.py

* Added type hints to jitter.py and resample.oy

* Updated black config file and reran on some files

* Added type hints to reverse.py and sidetrack.py

* Added type hints to the remaining source files
- Updated type hints in crop.py
- Fixed a few bugs in zoom.py

* Small cleanup of affine.py type hints

* Updated type hinting to support Python 3.5
Fixed bug in layer calc. All tests passing for 3.5 and 3.6

* added mypy test into CI/CD

* PR review fixes / cleanups

* Explicitly ignoring some type hint errors (line specific)
Removed some unused imports

* don't type numpy rand generator

* fixed type hinting errors related to _get_output_dim

* fixed a type hinting error

* fixed a type hinting error

* fixed a wrong type hint

* better code

* added some comment to explain what's going on

Co-authored-by: tailaiw <29800495+tailaiw@users.noreply.github.com>