Added type hints to augmentor.py and updated mypy.ini
augmentor.py still has the below error, which requires a fix:

src/tsaug/augmentor.py:212: error: Unsupported operand types for * ("None" and "int")
src/tsaug/augmentor.py:212: note: Left operand is of type "Optional[int]"